### ISSUE TITLE
imdb rating chayyan patto

### ISSUE THREAD

**Issue by IsmailUmmer** [sachin9742s/sachin-media-search-bot#1]
engane enkilum imdb rating koodi namukk kond varanam

**Comment by MRK-YT** [comment]
Mo Tech Kondu Vannu

**Comment by IsmailUmmer** [comment]
> Mo Tech Kondu Vannu

but ie repoil kaanan ilyallo vere private repo aano

**Comment by MRK-YT** [comment]
Ippo media Search Bot repo vannin
Adv Coming Soon 1 weekil Chillapol Verum Editing Fullum Complet aayin Nigalk Set akkan arayo nogal Ente PM Vaa Njan Demo Bot Kattikkam @PR0FESS0R_99 aan ente

**Comment by MRK-YT** [comment]
💡

**Comment by IsmailUmmer** [comment]
> 💡

Random Rating maatanam original Rating fetch chayyanam
